name: App deploy

on:
  push:
    branches: 
      - main
env:
  APP_FOLDER: applicatie
  SITE_FOLDER: site

jobs: 
  deploy-application:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.5.0
      - uses: copapow/version-bump-package@v1
        id: bump
        with:
          major_label: version-major # optional - default = major
          minor_label: version-minor # optional - default = minor
          patch_label: version-patch # optional - default = patch
          default_branch: main       # optional = default = master
          github_token: ${{ secrets.GITHUB_TOKEN }} # required
      - name: Setup Node.js environment
        if: false
        uses: actions/setup-node@v3.5.1
      - name: Generate site
        working-directory: ${{ env.SITE_FOLDER }}
        run: |
          npm install
          npm run build
      - name: Generate executable and deploy
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        working-directory: ${{ env.APP_FOLDER }}
        run: |
          npm install
          npm run build
          npm run publish



