name: App deploy

on:
  push:
    branches: 
      - main
env:
  APP_FOLDER: applicatie
  SITE_FOLDER: site

jobs: 
  deploy-application:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.5.0
      - name: Setup Node.js environment
        if: false
        uses: actions/setup-node@v3.5.1
      - name: Bumb package version
        working-directory: ${{ env.APP_FOLDER }}
        run: |
          npm version patch
          git commit "Update patch version"
          git push
      - name: Generate site
        working-directory: ${{ env.SITE_FOLDER }}
        run: |
          npm install
          npm run build
      - name: Generate executable and deploy
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        working-directory: ${{ env.APP_FOLDER }}
        run: |
          npm install
          npm run build
          npm run publish



