name: App deploy

on:
  push:
    branches: 
      - main
env:
  APP_FOLDER: applicatie
  SITE_FOLDER: site

jobs: 
  deploy-application:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.5.0
      - name: Increment Package.json Version
        # You may pin to the exact commit or the version.
        # uses: copapow/version-bump-package@d6f4d71c1b2a83b85a3d3404751896c8a048e650
        uses: copapow/version-bump-package@v
        with:
          # github token
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Setup Node.js environment
        if: false
        uses: actions/setup-node@v3.5.1
      - name: Bumb package version
        working-directory: ${{ env.APP_FOLDER }}
        run: |
          npm version patch
      - name: Generate site
        working-directory: ${{ env.SITE_FOLDER }}
        run: |
          npm install
          npm run build
      - name: Generate executable and deploy
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        working-directory: ${{ env.APP_FOLDER }}
        run: |
          npm install
          npm run build
          npm run publish



