name: App deploy

on:
  push:
    branches: 
      - main
env:
  APP_FOLDER: applicatie
  SITE_FOLDER: site

jobs: 
  deploy-application:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.5.0
      - name: Package Version Updated
        uses: MontyD/package-json-updated-action@1.0.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # The path to the package.json
          path: ${{ env.APP_FOLDER }}/package.json
      - name: Setup Node.js environment
        if: false
        uses: actions/setup-node@v3.5.1
      - name: Generate site
        working-directory: ${{ env.SITE_FOLDER }}
        run: |
          npm install
          npm run build
      - name: Generate executable and deploy
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        working-directory: ${{ env.APP_FOLDER }}
        run: |
          npm install
          npm run build
          npm run publish



