name: App deploy

on:
  push:
    branches: 
      - main

jobs: 
  deploy-application:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.5.0
      - name: Setup Node.js environment
        uses: actions/setup-node@v3.5.1
      - name: Generate executable
        run: echo hello
        
