name: App deploy

on:
  push:
    branches: 
      - main
env:
  FOLDER: Site

jobs: 
  deploy-application:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.5.0
      - name: Setup Node.js environment
        if: false
        uses: actions/setup-node@v3.5.1
      - name: Generate executable
        working-directory: ${{ env.FOLDER}}
        run: |
          ls
          npm install
          npm run
          
        
        
